name: qatarcyclists
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.5+9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  #UI
  base_notifier: ^0.0.4
  ui_utils:
  flutter_image_compress:
  intl: ^0.16.1
  auto_size_text: ^2.1.0
  
  dio: ^3.0.7
  file_picker: ^1.9.0+1 #TODO config ios
  image_picker: ^0.6.7+4
  stop_watch_timer:
  cached_video_player:
  flutter_video_info:

  flutter_cache_manager_firebase:
  share:
  url_launcher: ^5.5.0


  path_provider: ^1.3.0
  file_utils: ^0.1.3
  mime: ^0.9.6+3
  adobe_xd: ^0.1.4
  

  logger:
  provider:
  cloud_firestore: #TODO config ios
 # firebase_auth: ^0.16.1
  firebase_storage: ^3.1.1
  #audio_recorder: ^1.0.2
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1
  # firebase_core: #^0.4.4+3
  shared_preferences:
  fluttertoast: ^3.1.3
  firebase_messaging:
  overlay_support:
  location: ^3.0.2
  google_maps_flutter: ^0.5.26+4
  cached_network_image: ^2.0.0
  google_fonts: ^1.1.0
  data_connection_checker: ^0.3.4  
  device_info: ^0.4.1+4
  cupertino_icons: ^0.1.2
  geolocator: ^5.3.2+2
  # rxdart: ^0.24.1
  pull_to_refresh: ^1.5.8
  # flutter_rating_bar: ^3.0.1+1
  carousel_slider: ^2.1.0
  html: ^0.14.0+4


  # firebase_storage: ^3.1.1 #TODO config ios
  # mime: ^0.9.6+3
  # intl: ^0.16.0
  # firebase_messaging: ^6.0.9 #TODO config ios
  # transformer_page_view: ^0.1.6
  permission_handler: ^5.0.0+hotfix.3 #TODO config ios


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/languages/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
